apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-boathouse
  name: hello-boathouse-lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: hello-boathouse
status:
  loadBalancer: {}